package graphgen

var (
	Font3x3 = Font{
		'A': {
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'B': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'C': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'D': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
		},
		'E': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'F': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
		},
		'G': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'H': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'I': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'J': {
			{EmptyCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'K': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'L': {
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'M': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'N': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'O': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'P': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
		},
		'Q': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'R': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
		},
		'S': {
			{EmptyCell, OccupiedCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
		},
		'T': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'U': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'V': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'W': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'X': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'Y': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'Z': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, OccupiedCell},
		},
		' ': {
			{EmptyCell},
			{EmptyCell},
			{EmptyCell},
		},
		'1': {
			{OccupiedCell, EmptyCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'2': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, OccupiedCell},
		},
		'3': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'4': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'5': {
			{EmptyCell, OccupiedCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
		},
		'6': {
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'7': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'8': {
			{EmptyCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'9': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'0': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
	}

	Font3x5 = Font{
		'A': {
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'B': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
		},
		'C': {
			{EmptyCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{EmptyCell, OccupiedCell, OccupiedCell},
		},
		'D': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
		},
		'E': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'F': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
		},
		'G': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'H': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'I': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'J': {
			{EmptyCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'K': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'L': {
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'M': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'N': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'O': {
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'P': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
		},
		'Q': {
			{EmptyCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'R': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'S': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'T': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'U': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'V': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'W': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'X': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
		},
		'Y': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'Z': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		' ': {
			{EmptyCell},
			{EmptyCell},
			{EmptyCell},
			{EmptyCell},
			{EmptyCell},
		},
		'1': {
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'2': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'3': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'4': {
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'5': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'6': {
			{OccupiedCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, EmptyCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
		},
		'7': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'8': {
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
		'9': {
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, OccupiedCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
			{EmptyCell, EmptyCell, OccupiedCell},
		},
		'0': {
			{EmptyCell, OccupiedCell, EmptyCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{OccupiedCell, EmptyCell, OccupiedCell},
			{EmptyCell, OccupiedCell, EmptyCell},
		},
	}
)
